
[window]
opacity = 0.90
[font]
normal = {family = "Iosevka", style = "Regular"}
size = 13
[cursor]
style = {shape = "Block", blinking = "On"}
blink_timeout = 0
blink_interval = 750
unfocused_hollow = false
smooth_motion = true
smooth_motion_factor = 0.7
smooth_motion_spring = 0.6
smooth_motion_max_stretch_x = 3.0
smooth_motion_max_stretch_y = 3.0
[mouse]
hide_when_typing = true
[colors]
cursor = {text = "0x000000", cursor = "#ff7eb6"}
[env]
TERM = "xterm-256color"

[general]
import = [
	"~/.config/alacritty/oxocarbon.toml"
]
